### ISSUE TITLE
Error reading SAC files local network

### ISSUE THREAD

**Issue by indraPLM** [mtuqorg/mtuq#284]
Dear All,

I am newbie for using MTUQ software. I interest to use MTUQ to estimate moment tensor crustal earthquake magnitude ranging from4 to 5.5 . I tried to use SAC files seismic records from our local seismic network. Unfortunately, it's seem I get problem in reading the SAC files. Here is the error message: 
(mtuq) sysop@sysop:~/mtuq/examples$ python [SerialGridSearch.DoubleCouple.py](http://serialgridsearch.doublecouple.py/)
Reading data...

Traceback (most recent call last):
  File "/home/indra/mtuq/examples/[SerialGridSearch.DoubleCouple.py](http://serialgridsearch.doublecouple.py/)", line 137, in <module>
    data = read(path_data, format='sac',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/indra/mtuq/mtuq/__init__.py", line 95, in read
    return _readers()[format](path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/indra/mtuq/mtuq/io/readers/SAC.py", line 79, in read
    assert preliminary_origin==_get_origin(stream, event_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Meanwhile, when I only use single station SAC File, the SerialGridSearch.DoubleCouple.py run well and could process for obtaining green function. 
Hopefully, I could get advise and suggestion to fix the problem.
Warm Regards

Indra Gunawan

**Comment by indraPLM** [comment]
Dear Ryan,

Really, I don't know well, how to fix the problem.  
I already compared SAC header from our SAC Files with data/example/2009040720125535. It seems all features in SAC header  are available.
Here I attached our SAC files, perhaps you could try.

Warm Regards
Indra Gunawan
[20221121062110565.zip](https://github.com/user-attachments/files/17870558/20221121062110565.zip)

**Comment by indraPLM** [comment]
Ok I get it. It seem work to read SAC files and mtuq is running well. 

Thank you so much.

**Comment by rmodrak** [comment]
Great, glad to hearOn Nov 22, 2024, at 7:01 AM, indraPLM ***@***.***> wrote:﻿
Ok I get it. It seem work to read SAC files and mtuq is running well.
Thank you so much.
